### ISSUE TITLE
Chords display

### ISSUE THREAD

**Issue by macpra** [vwout/os-secondscreen#1]
It's about chords. Chords are not displayed exactly where they are entered in the opensong editor. I don't know if I will be understood. English is not my forte. In the photo below you can see what I mean. On the left view from os-secondscreen, on the right - opensong editor.

![image](https://user-images.githubusercontent.com/82063137/114379708-6909b200-9b89-11eb-9f93-24c8910df72d.png)

**Comment by vwout** [comment]
The chords (and many other things) were incorrectly centered. It should be fixed now.
